# Generated by Django 4.1.7 on 2023-03-14 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': "Ma'lumot",
                'verbose_name_plural': "Ma'lumotlar",
            },
        ),
    ]
